### ISSUE TITLE
MySQL and bro-pdns

### ISSUE THREAD

**Issue by lanternsec** [JustinAzoff/bro-pdns#1]
It looks like VARCHAR fields need to have a length specified if writing to MySQL through sqlalchemy:

1419743701.305919       0       Traceback (most recent call last):,  File "/opt/bro/share/bro/site/bro-pdns/bro_pdns.py"\x2c line 237\x2c in <module>,    func(),  File "/opt/bro/share/bro/site/bro-pdns/bro_pdns.py"\x2c line185\x2c in process,    process_fn(f),  File "/opt/bro/share/bro/site/bro-pdns/bro_pdns.py"\x2c line 179\x2c in process_fn,    processed = sum(pool.imap(load_records\x2c batches\x2c chunksize=1)),  File "/usr/lib/python2.7/multiprocessing/pool.py"\x2c line 626\x2c in next,    raise value,sqlalchemy.exc.InvalidRequestError: VARCHAR requires a length on dialect mysql

This was easy enough to fix, although I probably did not choose ideal values, when modifying bro-pdns.py and adding lengths to the String columns:

dns_table = Table('dns', metadata,
    Column('query', String(255), primary_key=True, index=True),
    Column('type', String(16), primary_key=True),
    Column('answer', String(255), primary_key=True, index=True),
    Column('count', Integer),
    Column('ttl', Integer),
    Column('first', DateTime),
    Column('last', DateTime),
)

**Comment by JustinAzoff** [comment]
Gah, dropped the ball on this. I'll get this updated
