### ISSUE TITLE
json support?

### ISSUE THREAD

**Issue by villain** [JustinAzoff/bro-pdns#2]
is there any plans to add support for the JSON logs bro produces?

**Comment by JustinAzoff** [comment]
Yes.. I'm working on a faster+better rewrite in go, I can add that feature in next. I'll probably be able to support raw-pcaps too down the road so I may need to rename the project :-)

**Comment by JustinAzoff** [comment]
Initial json support added in https://github.com/JustinAzoff/bro-pdns/tree/feat/json

**Comment by JustinAzoff** [comment]
Merged back in 53a53a1fabf8b6a1729023f732a83999820eafce
