### ISSUE TITLE
I do not understand how I should I install and use this tool?

### ISSUE THREAD

**Issue by elico** [JustinAzoff/bro-pdns#6]
Are there any installation instructions?
I have an Ubunut 16.04 router with bind\unbound installed and running(can start and stop each of them).
This is the first time I have seen this repository and It's kind of hard for me to grasp how it should be installed on my setup.
I tried to lookup here and there are found this article: https://nullsecure.org/building-your-own-passivedns-feed/
but I couldn't understand how it works out with the current main branch which is written GoLang.
I have used elastic packetbeat to log dns queries to ELK\Graylog and it's usefull but it uses lots of resources and I was wondering I might get some directions\instructions that will help me to replace packetbeat with bro-pdns.

**Comment by JustinAzoff** [comment]
bro-pdns is for aggregating and indexing the dns logs produced by https://www.bro.org/

Bro is kind of like packetbeat.

If you are not currently running bro then bro-pdns won't do anything useful for you.  It could probably be extended to support the packetbeat dns logs or pcap directly, but for now it only works with bro logs.

**Comment by elico** [comment]
@JustinAzoff thanks, it clear out things for me.
