### ISSUE TITLE
Starting Bro is failing

### ISSUE THREAD

**Issue by antwanvanderstap** [JustinAzoff/bro-pdns#7]
I have searched for answers, did a complete new install (Ubuntu and Bro) 
Still getting errors:
[BroControl] > start
starting bro ...
bro terminated immediately after starting; check output with "diag"
[BroControl] > diag
[bro]

Bro 2.4.1
Linux 4.4.0-121-generic

==== No reporter.log

==== stderr.log
fatal error in /nsm/bro/spool/installed-scripts-do-not-touch/site/./bro-pdns/__load__.bro, line 1: can't find ./passive-dns

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-i eth0 -U .status -p broctl -p broctl-live -p standalone -p local -p bro local.bro broctl broctl/standalone broctl/auto

==== .env_vars
PATH=/nsm/bro/bin:/nsm/bro/share/broctl/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
BROPATH=/nsm/bro/spool/installed-scripts-do-not-touch/site::/nsm/bro/spool/installed-scripts-do-not-touch/auto:/nsm/bro/share/bro:/nsm/bro/share/bro/policy:/nsm/bro/share/bro/site
CLUSTER_NODE=

==== .status
TERMINATED [atexit]

==== No prof.log

==== No packet_filter.log

Any 'fish' or 'teaching how to fish' is a appreciated!
Thanks and cheers, Antwan

**Comment by JustinAzoff** [comment]
Ah, that's my fault.. that __load__ file isn't used anymore and should have been deleted.

bro-pdns just indexes the existing bro logs now, so there are no changes required on the bro side.

**Comment by JustinAzoff** [comment]
Hi!

Were you able to get it working?  You basically just need to get bro-pdns going and run

    bro-pdns index /usr/local/bro/logs/*/dns*.gz

**Comment by antwanvanderstap** [comment]
I feel terrible for not following up Justin - not cool from my end.
Please accept my apologies!!

**Comment by JustinAzoff** [comment]
That's ok :-)  Were you able to get it working?

**Comment by antwanvanderstap** [comment]
To be honest - my day job got in the way and had to move on for now.
Will attempt again after dessert summer camp ;-)

**Comment by JustinAzoff** [comment]
Fair enough :)  I'm going to work on some packaging and documentation improvements soon, so things should be a little better the next time you look.

**Comment by antwanvanderstap** [comment]
Will definitely come back to this as it looks extremely promising.
Thanks for your work and contribution to the community
